export const ADD_APPLIANCE = "ADD_APPLIANCE";
export const REMOVE_APPLIANCE = "REMOVE_APPLIANCE";
export const ADD_OTHER_APPLIANCES = "ADD_OTHER_APPLIANCES";
export const INVERTER_NEEDED = "INVERTER_NEEDED";
export const AVERAGE_POWER_NEEDED = "AVERAGE_POWER_NEEDED";
export const TOTAL_WATTAGE = "TOTAL_WATTAGE";
